CREATE VIEW Subject_ML AS
SELECT
        SUBJECT.NDG
        ,SUBJECT.BIRTH_DAY
        ,SUBJECT.LEGAL_SPECIE
        ,SUBJECT.RESIDENCE_CAB
        ,SUBJECT.RESIDENCE_CAP
        ,SUBJECT.RESIDENCE_PROVINCE
        ,SUBJECT.RESIDENCE_CITY
        ,SUBJECT.RESIDENCE_COUNTRY
        ,SUBJECT.SAE
        ,SUBJECT.ATECO
        ,SUBJECT.SSE
        ,SUBJECT.RISK_PROFILE
        ,SUBJECT.FIRST_CONTACT_DATE
        ,SUBJECT.STATUS
        ,SUBJECT.REPORTED
        ,SUBJECT.PREJUDICIAL
        ,SUBJECT.NCHECKREQUIRED
        ,SUBJECT.NCHECKDEBITED
        ,SUBJECT.NCHECKAVAILABLE
        ,SUBJECT.PORTFOLIO
        ,SUBJECT.INSERT_DATE
        ,SUBJECT.LAST_UPDATE_DATE
        ,SUBJECT.GROSS_INCOME
		,SUBJECT.GROSS_INCOME_WAGE
        ,SUBJECT.SETTLEMENT_DATE
        FROM SUBJECT
        WHERE  SUBJECT.CODE_INTERMEDIARY = %s;
CREATE VIEW Account_ML AS
SELECT DISTINCT ACCOUNT.CODE_ACCOUNT
        ,ACCOUNT.START_DATE
        ,ACCOUNT.EXPIRE_DATE
        ,ACCOUNT_SUBJECT.NDG
FROM ACCOUNT INNER JOIN  ACCOUNT_SUBJECT ON ACCOUNT.CODE_ACCOUNT =  ACCOUNT_SUBJECT.CODE_ACCOUNT
WHERE ACCOUNT_SUBJECT.CODE_INTERMEDIARY = %s;
CREATE VIEW Operations_Subjects_ML as
SELECT
      CODE_OPERATION
     ,NDG
     ,SUBJECT_TYPE
FROM OPERATION_SUBJECT
WHERE CODE_INTERMEDIARY = %s;
CREATE VIEW Operations_ML AS
SELECT OPERATION.CODE_OPERATION
     ,OPERATION.ACCOUNT
     ,OPERATION.ACCOUNT_SUBTYPE
     ,OPERATION.ACCOUNT_RELATION
     ,OPERATION.DATE_OPERATION
     ,OPERATION.CAUSAL
     ,OPERATION.SUBCAUSAL
     ,OPERATION.SIGN
     ,OPERATION.FLAG_FRACTION
     ,OPERATION.FLAG_CASH
     ,OPERATION.AMOUNT
     ,OPERATION.AMOUNT_CASH
     ,OPERATION.COUNTRY
     ,OPERATION.CURRENCY
     ,OPERATION.CURRENCY_TYPE
     ,OPERATION.CONSOLIDATION_DATE
     ,OPERATION.TRANSACTION_CODE
     ,OPERATION.TRANSACTION_TYPE
     ,OPERATION.COUNTERPART_TYPE
     ,OPERATION.COUNTERPART_CODE
     ,OPERATION.COUNTERPART_CAB
     ,OPERATION.COUNTERPART_PROVINCE
     ,OPERATION.COUNTERPART_CITY
     ,OPERATION.COUNTERPART_COUNTRY
     ,OPERATION.COUNTERPART_ACCOUNT
     ,OPERATION.COUNTERPART_SUBJECT_COUNTRY
     ,OPERATION.FILIAL
FROM OPERATION
WHERE OPERATION.CODE_INTERMEDIARY = %s