CREATE VIEW Operations_day_info AS
SELECT DISTINCT OPERATION_SUBJECT.NDG,
        OPERATION.CODE_OPERATION,
        OPERATION.DATE_OPERATION,
        OPERATION.CAUSAL,
        OPERATION.SIGN,
        OPERATION.COUNTRY,
        OPERATION.AMOUNT,
        OPERATION.AMOUNT_CASH,
        OPERATION.COUNTERPART_SUBJECT_COUNTRY,
        OPERATION_SUBJECT.SUBJECT_TYPE,
        SUBJECT.RESIDENCE_COUNTRY as 'RESIDENCE_COUNTRY_T',
        SUBJECT.RISK_PROFILE as 'RISK_PROFILE_T',
        E.NDG as 'NDG_E',
        E.SUBJECT_TYPE as 'SUBJECT_TYPE_E',
        S.RESIDENCE_COUNTRY as 'RESIDENCE_COUNTRY_E',
        S.RISK_PROFILE as 'RISK_PROFILE_E'

        FROM OPERATION
        left join OPERATION_SUBJECT on OPERATION.CODE_OPERATION = OPERATION_SUBJECT.CODE_OPERATION
        left join SUBJECT on OPERATION_SUBJECT.NDG = SUBJECT.NDG
        right join OPERATION_SUBJECT E on OPERATION.CODE_OPERATION = E.CODE_OPERATION
        left join SUBJECT S on E.NDG = S.NDG

        WHERE OPERATION.CODE_INTERMEDIARY = %s and
        OPERATION_SUBJECT.SUBJECT_TYPE = 'T' and
        E.SUBJECT_TYPE != 'F';
CREATE VIEW Subject_ML AS
SELECT
        SUBJECT.NDG
        ,SUBJECT.BIRTH_DAY
        ,SUBJECT.LEGAL_SPECIE
        ,SUBJECT.RESIDENCE_CAB
        ,SUBJECT.RESIDENCE_CAP
        ,SUBJECT.RESIDENCE_PROVINCE
        ,SUBJECT.RESIDENCE_CITY
        ,SUBJECT.RESIDENCE_COUNTRY
        ,SUBJECT.SAE
        ,SUBJECT.ATECO
        ,SUBJECT.SSE
        ,SUBJECT.RISK_PROFILE
        ,SUBJECT.FIRST_CONTACT_DATE
        ,SUBJECT.STATUS
        ,SUBJECT.REPORTED
        ,SUBJECT.PREJUDICIAL
        ,SUBJECT.NCHECKREQUIRED
        ,SUBJECT.NCHECKDEBITED
        ,SUBJECT.NCHECKAVAILABLE
        ,SUBJECT.PORTFOLIO
        ,SUBJECT.INSERT_DATE
        ,SUBJECT.LAST_UPDATE_DATE
        ,SUBJECT.GROSS_INCOME
        ,SUBJECT.SETTLEMENT_DATE
        FROM SUBJECT
        WHERE  SUBJECT.CODE_INTERMEDIARY = %s;
CREATE VIEW Account_ML AS
SELECT DISTINCT ACCOUNT.CODE_ACCOUNT
        ,ACCOUNT.START_DATE
        ,ACCOUNT.EXPIRE_DATE
        ,ACCOUNT_SUBJECT.NDG
FROM ACCOUNT INNER JOIN  ACCOUNT_SUBJECT ON ACCOUNT.CODE_ACCOUNT =  ACCOUNT_SUBJECT.CODE_ACCOUNT
WHERE ACCOUNT_SUBJECT.CODE_INTERMEDIARY = %s;
CREATE VIEW Operations_ML AS
SELECT DISTINCT OPERATION_SUBJECT.NDG
        ,OPERATION.CODE_OPERATION
        ,OPERATION.CODE_FLUX
        ,OPERATION.ACCOUNT
        ,OPERATION.ACCOUNT_SUBTYPE
        ,OPERATION.ACCOUNT_RELATION
        ,OPERATION.DATE_OPERATION
        ,OPERATION.CAUSAL
        ,OPERATION.SUBCAUSAL
        ,OPERATION.SIGN
        ,OPERATION.FLAG_FRACTION
        ,OPERATION.FLAG_CASH
        ,OPERATION.AMOUNT
        ,OPERATION.AMOUNT_CASH
        ,OPERATION.COUNTRY
        ,OPERATION.CURRENCY
        ,OPERATION.CURRENCY_TYPE
        ,OPERATION.CONSOLIDATION_DATE
        ,OPERATION.TRANSACTION_CODE
        ,OPERATION.TRANSACTION_TYPE
        ,OPERATION.COUNTERPART_TYPE
        ,OPERATION.COUNTERPART_CODE
        ,OPERATION.COUNTERPART_CAB
        ,OPERATION.COUNTERPART_PROVINCE
        ,OPERATION.COUNTERPART_CITY
        ,OPERATION.COUNTERPART_COUNTRY
        ,OPERATION.COUNTERPART_ACCOUNT
        ,OPERATION.COUNTERPART_SUBJECT_COUNTRY
        ,OPERATION.FILIAL
        FROM OPERATION
        INNER JOIN  OPERATION_SUBJECT ON OPERATION.CODE_OPERATION =  OPERATION_SUBJECT.CODE_OPERATION
        WHERE  OPERATION_SUBJECT.SUBJECT_TYPE = 'T' AND OPERATION.CODE_INTERMEDIARY = %s;
CREATE VIEW Operations_day_info_2 AS
SELECT *
FROM Operations_day_info
WHERE (NDG = NDG_E and SUBJECT_TYPE_E = 'T') or (NDG != NDG_E and SUBJECT_TYPE_E = 'E') or (NDG = NDG_E and SUBJECT_TYPE_E = 'E');
CREATE VIEW Operations_day_ML AS
SELECT	NDG,
        CODE_OPERATION,
        DATE_OPERATION,
        CAUSAL,
        SIGN,
        COUNTRY,
        AMOUNT,
        AMOUNT_CASH,
        COUNTERPART_SUBJECT_COUNTRY,
        RESIDENCE_COUNTRY_T,
        RESIDENCE_COUNTRY_E,
        RISK_PROFILE_E

        FROM Operations_day_info_2

        WHERE ((SELECT count(*) FROM OPERATION_SUBJECT E2 where E2.CODE_OPERATION = Operations_day_info_2.CODE_OPERATION and E2.SUBJECT_TYPE='E') > 0 and Operations_day_info_2.SUBJECT_TYPE_E != 'T') or
        ((SELECT count(*) FROM OPERATION_SUBJECT E2 where E2.CODE_OPERATION = Operations_day_info_2.CODE_OPERATION and E2.SUBJECT_TYPE='E') = 0);
CREATE VIEW input_ML as
SELECT *
FROM ;