/****** Script for SelectTopNRows command from SSMS  ******/
SELECT DISTINCT [mm_dwa].[dbo].[OPERATION_SUBJECT].[NDG] 
	  ,[mm_dwa].[dbo].[OPERATION].[CODE_OPERATION]
      ,[mm_dwa].[dbo].[OPERATION].[CODE_FLUX]
      ,[mm_dwa].[dbo].[OPERATION].[ACCOUNT]
      ,[mm_dwa].[dbo].[OPERATION].[ACCOUNT_SUBTYPE]
      ,[mm_dwa].[dbo].[OPERATION].[ACCOUNT_RELATION]
      ,[mm_dwa].[dbo].[OPERATION].[DATE_OPERATION]
      ,[mm_dwa].[dbo].[OPERATION].[CAUSAL]
      ,[mm_dwa].[dbo].[OPERATION].[SUBCAUSAL]
      ,[mm_dwa].[dbo].[OPERATION].[SIGN]
      ,[mm_dwa].[dbo].[OPERATION].[FLAG_FRACTION]
      ,[mm_dwa].[dbo].[OPERATION].[FLAG_CASH]
      ,[mm_dwa].[dbo].[OPERATION].[AMOUNT]
      ,[mm_dwa].[dbo].[OPERATION].[AMOUNT_CASH]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTRY]
      ,[mm_dwa].[dbo].[OPERATION].[CURRENCY]
      ,[mm_dwa].[dbo].[OPERATION].[CURRENCY_TYPE]
      ,[mm_dwa].[dbo].[OPERATION].[CONSOLIDATION_DATE]
      ,[mm_dwa].[dbo].[OPERATION].[TRANSACTION_CODE]
      ,[mm_dwa].[dbo].[OPERATION].[TRANSACTION_TYPE]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_TYPE]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_CODE]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_CAB]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_PROVINCE]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_CITY]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_COUNTRY]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_ACCOUNT]
      ,[mm_dwa].[dbo].[OPERATION].[COUNTERPART_SUBJECT_COUNTRY]
	  ,[mm_dwa].[dbo].[OPERATION].[FILIAL]
  FROM [mm_dwa].[dbo].[OPERATION]
  INNER JOIN  [mm_dwa].[dbo].[OPERATION_SUBJECT] ON [mm_dwa].[dbo].[OPERATION].[CODE_OPERATION] =  [mm_dwa].[dbo].[OPERATION_SUBJECT].[CODE_OPERATION] 

  WHERE  [mm_dwa].[dbo].[OPERATION_SUBJECT].[SUBJECT_TYPE] = 'T' AND [mm_dwa].[dbo].[OPERATION].[CODE_INTERMEDIARY] = '060459'
  order by [mm_dwa].[dbo].[OPERATION].[DATE_OPERATION]
