SELECT DISTINCT 
	   ACCOUNT.CODE_ACCOUNT
      ,ACCOUNT.START_DATE
      ,ACCOUNT.EXPIRE_DATE
	  ,ACCOUNT_SUBJECT.NDG
FROM ACCOUNT
  INNER JOIN  ACCOUNT_SUBJECT ON ACCOUNT.CODE_ACCOUNT =  ACCOUNT_SUBJECT.CODE_ACCOUNT
WHERE ACCOUNT_SUBJECT.CODE_INTERMEDIARY = '060459'