SELECT
	   SUBJECT.NDG
	  ,SUBJECT.BIRTH_DAY
      ,SUBJECT.LEGAL_SPECIE
      ,SUBJECT.RESIDENCE_CAB
      ,SUBJECT.RESIDENCE_CAP
      ,SUBJECT.RESIDENCE_PROVINCE
      ,SUBJECT.RESIDENCE_CITY
      ,SUBJECT.RESIDENCE_COUNTRY
      ,SUBJECT.SAE
      ,SUBJECT.ATECO
      ,SUBJECT.SSE
      ,SUBJECT.RISK_PROFILE
      ,SUBJECT.FIRST_CONTACT_DATE
      ,SUBJECT.STATUS
	  ,SUBJECT.REPORTED
	  ,SUBJECT.PREJUDICIAL
	  ,SUBJECT.NCHECKREQUIRED
      ,SUBJECT.NCHECKDEBITED
      ,SUBJECT.NCHECKAVAILABLE
      ,SUBJECT.PORTFOLIO
      ,SUBJECT.INSERT_DATE
      ,SUBJECT.LAST_UPDATE_DATE
      ,SUBJECT.GROSS_INCOME
	  ,SUBJECT.GROSS_INCOME_WAGE
      ,SUBJECT.SETTLEMENT_DATE
FROM SUBJECT
WHERE  SUBJECT.CODE_INTERMEDIARY = '060459'
