(SELECT A.ID, D.CREATION_DATE, D.FILENAME
FROM  (ANOMALY as A left join ANOMALY_SEARCH_SUBJECT as ASS on A.ID = ASS.ANOMALY_ID)
	   left join DOCUMENT as D on ASS.ID = D.EVALUATION_ID
WHERE SYSTEM_ID = 'DISCOVERY' and D.FILENAME is not null)
UNION
(SELECT A.ID, D.CREATION_DATE, D.FILENAME
FROM (ANOMALY as A left join ANOMALY_SEARCH_SUBJECT as ASS on A.ID = ASS.ANOMALY_ID)
	  left join DOCUMENT as D on ASS.ID = D.EVALUATION_ID
WHERE SYSTEM_ID = 'COMPORTAMENT' and D.FILENAME is not null)
ORDER BY ID