(SELECT A.ID
	  ,A.CODE
	  ,A.SYSTEM_ID
	  ,A.AMOUNT
      ,A.FIRSTSAVE
	  ,A.STATUS_ID     
	  ,ASS.NDG
	  ,ASO.A21
	  ,ASO.A03
FROM  (ANOMALY as A left join ANOMALY_SEARCH_OPERATION as ASO on A.ID = ASO.ANOMALY_ID)
	  left join ANOMALY_SEARCH_SUBJECT as ASS on A.ID = ASS.ANOMALY_ID
where SYSTEM_ID = 'DISCOVERY')
UNION
(SELECT A.ID
	  ,A.CODE
	  ,A.SYSTEM_ID
	  ,A.AMOUNT
      ,A.FIRSTSAVE
	  ,A.STATUS_ID     
	  ,ASS.NDG
	  ,NULL as A21
	  ,NULL as A03
FROM ANOMALY as A left join ANOMALY_SEARCH_SUBJECT as ASS on A.ID = ASS.ANOMALY_ID
where SYSTEM_ID = 'COMPORTAMENT')
ORDER BY FIRSTSAVE