(SELECT A.ID , E.CREATION_DATE, E.BODY
FROM ANOMALY as A left join EVALUATION as E on A.ID = E.ANOMALY_ID
WHERE SYSTEM_ID = 'DISCOVERY')
UNION
(SELECT A.ID , E.CREATION_DATE, E.BODY
FROM ANOMALY as A left join EVALUATION as E on A.ID = E.ANOMALY_ID
WHERE SYSTEM_ID = 'COMPORTAMENT')
ORDER BY ID