/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
	   [mm_dwa].[dbo].[SUBJECT].[NDG]
	  ,[mm_dwa].[dbo].[SUBJECT].[BIRTH_DAY]
      ,[mm_dwa].[dbo].[SUBJECT].[LEGAL_SPECIE]
      ,[mm_dwa].[dbo].[SUBJECT].[RESIDENCE_CAB]
      ,[mm_dwa].[dbo].[SUBJECT].[RESIDENCE_CAP]
      ,[mm_dwa].[dbo].[SUBJECT].[RESIDENCE_PROVINCE]
      ,[mm_dwa].[dbo].[SUBJECT].[RESIDENCE_CITY]
      ,[mm_dwa].[dbo].[SUBJECT].[RESIDENCE_COUNTRY]
      ,[mm_dwa].[dbo].[SUBJECT].[SAE]
      ,[mm_dwa].[dbo].[SUBJECT].[ATECO]
      ,[mm_dwa].[dbo].[SUBJECT].[SSE]
      ,[mm_dwa].[dbo].[SUBJECT].[RISK_PROFILE]
      ,[mm_dwa].[dbo].[SUBJECT].[FIRST_CONTACT_DATE]
      ,[mm_dwa].[dbo].[SUBJECT].[STATUS]
	  ,[mm_dwa].[dbo].[SUBJECT].[REPORTED]
	  ,[mm_dwa].[dbo].[SUBJECT].[PREJUDICIAL]
	  ,[mm_dwa].[dbo].[SUBJECT].[NCHECKREQUIRED]
      ,[mm_dwa].[dbo].[SUBJECT].[NCHECKDEBITED]
      ,[mm_dwa].[dbo].[SUBJECT].[NCHECKAVAILABLE]
      ,[mm_dwa].[dbo].[SUBJECT].[PORTFOLIO]
      ,[mm_dwa].[dbo].[SUBJECT].[INSERT_DATE]
      ,[mm_dwa].[dbo].[SUBJECT].[LAST_UPDATE_DATE]
      ,[mm_dwa].[dbo].[SUBJECT].[GROSS_INCOME]
      ,[mm_dwa].[dbo].[SUBJECT].[SETTLEMENT_DATE]
  FROM [mm_dwa].[dbo].[SUBJECT]
  WHERE  [mm_dwa].[dbo].[SUBJECT].[CODE_INTERMEDIARY] = '060459'
